# 开发环境配置文件
debug: true
host: "0.0.0.0"
port: 8000

# 数据库配置
database:
  type: sqlite
  path: database/metadata.db

# 查询引擎配置
query_engine:
  type: duckdb
  path: database/business.duckdb

# LLM配置
llm:
  provider: openai
  base_url: "${LLM_BASE_URL}"
  api_key: "${LLM_API_KEY}"
  model: gpt-4-turbo
  temperature: 0.1
  max_tokens: 4000

# 向量数据库配置
vector_db:
  path: database/vector_db
  collection: taosha_knowledge

# 查询配置
query:
  timeout: 30
  max_retry_count: 3
  max_result_rows: 1000

# 日志配置
log:
  level: INFO
  file: logs/taosha.log

# 安全配置
security:
  secret_key: "dev-secret-key-change-in-production"
  allowed_origins:
    - "http://localhost:3000"
    - "http://127.0.0.1:3000"
  allowed_hosts:
    - "localhost"
    - "127.0.0.1"